name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: sudo apt-get -y install libproxy-dev
      - run: bundle exec rake
